estuary/animated-carnival

ops-catalog/.gitignore
ops-catalog/README.md
ops-catalog/derivations.flow.ts
ops-catalog/derivations.flow.yaml
ops-catalog/greeting-schema.yaml
ops-catalog/local.flow.yaml
ops-catalog/mock-tasks.flow.yaml
ops-catalog/ops-log-schema.json
ops-catalog/ops-shard-schema.json
ops-catalog/ops-stats-schema.json
ops-catalog/package.json
ops-catalog/prod.flow.yaml
ops-catalog/stats-materialization-endpoint.sops.yaml
supabase/migrations/10_stats.sql

This adds a database migration that adds new tables to hold flow task
stats, and a flow catalog that materializes the stats to those tables.
The resulting tables can be queried via the REST API.

Materialize task stats into the control plane DB

---

readme.md

I tried to get the control plane working today and hit an issue where I didn't have fetch-open-graph built at the location where the flow binaries lived. Added a mention in the README to build the binary. Not sure if it should have been in dependency as the code is inside this repo.
If you want to re-reword, feel free.

Add fetch-open-graph to the README

---

readme.md
supabase/migrations/14_gateway_auth.sql

Adds the `gateway_auth_token` rpc. This will use the user's role prefixes to generate a JWT (with [`pgjwt`](https://github.com/michelp/pgjwt) pre-installed by Supabase) that can be passed to the Data Plane Gateway. We only support `read` operations right now, as it isn't clear how a user can usefully use the other Gazette endpoints. Tokens expire after an hour, but this was arbitrary.
This also adds a couple of internal tables for configuring the behavior of this token. If there's a better way to handling injecting configuration/secrets into postgres functions, I'm all ears.

Generate Data Plane Gateway auth tokens

---

crates/agent-sql/src/publications.rs
crates/agent/src/connector_tags.rs
crates/agent/src/publications.rs
crates/agent/src/publications/builds.rs
crates/agent/src/publications/specs.rs
supabase/migrations/09_publications.sql
supabase/seed.sql

`last_build_id` is the publication which last caused a spec to be built
and activated into the data-plane.
Update publication behavior to keep this column up-to-date given the
expanded set of catalog specifications.
Use `last_build_id` to identify the correct build DB for data-plane
deletions.
Tested:
* Started a local control-plane + data-plane, with a side Postgres DB
* Create a capture and multiple materializations over a period of time,
with staggered deletions of materializations while creating others.
* Deleted all remaining tasks, and verified that all ApplyDelete RPCs
were run and all shards were removed, leaving an empty data-plane.
Issue #24

add `last_build_id` to `live_specs` to resolve phantom deletions

---

local/start-component.sh
local/start-flow.sh
readme.md

Previously, a locally running Flow instance would still use the
production config-encryption service. This fixes that so a local
instance of config-encryption is run alongside the other services.
This will require a complimentary PR in the UI to point the local
UI to the local config-encryption service.
Fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/39)

Add config-encryption service to local instance

---

local/start-component.sh

Use `flowctl-admin` to start the `temp-data-plane` in `start-component.sh`.
Building from scratch, I found that the `start-flow.sh` script was failing because `flowctl` could not be found, and this fixed it for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/41)

Fix start-component.sh to use flowctl-admin

---

readme.md

Fixes some links that were not working. Also updates the instructions for `Supabase CLI` - the version in our specific instructions was out of date, but the instructions at the supabase repo link worked well for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/40)

update dependencies links

---

crates/agent/src/publications/builds.rs
scripts/seed_connectors.sql

This ensures the build database exists in cloud storage in the event that we fail to inspect the `errors` table. This is indicative of a bug elsewhere, but it's difficult to investigate when the database isn't uploaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/37)

Ensure Builds Persist

---

readme.md

Having not used `go` in many years, I got confused when I followed the instructions, and there was no `data-plane-gateway` binary. Turns out you need to run `go build` to get it!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/46)

docs: Add missing `go build` command to readme

---

supabase/functions/oauth/encrypt-config.ts

I ran into this when getting started with Flow locally on a call today with @travjenkins, and this is the fix we came up with. I haven't fully read all of this code, so if this fix is actually not the right thing to do, please let me know :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/48)

fix: Add optional chaining to prevent exceptions when `config` is missing

---

supabase/functions/oauth/access-token.ts
supabase/functions/oauth/encrypt-config.ts
supabase/migrations/06_connectors.sql
supabase/pending/oauth.sql

Allow injecting arbitrary secret keys into credentials and templates.
One potential change here is to consolidate `client_id` and `client_secret` into the same `oauth2_injected_values`, what do you folks think?
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/50)

oauth2: allow injecting arbitrary values to connector for oauth2

---

supabase/functions/oauth/access-token.ts

depends on: https://github.com/estuary/flow/pull/633
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/52)

oauth2: allow non-json access token bodies

---

readme.md

This came out of a conversation with @jgraettinger about the intended use of the `supabase/pending/` directory, which was previously undocumented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/55)

clarify use of pending directory for migrations

---

supabase/functions/_shared/helpers.ts
supabase/functions/oauth/access-token.ts
supabase/functions/oauth/auth-url.ts

This helper can be used in templates as:
```
{{ urlencode client_id }}
```
This is useful when sending a url encoded POST body, to escape special characters. Example usage in [salesforce](https://github.com/estuary/airbyte/commit/29d0c93f7d645e102e84e268910fe4b1c7730527).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/54)

oauth: add "urlencode" helper to handlebars templates

---

local/start-component.sh

I had forgotten to add that argument when I wrote the script. Without it, connectors can't connect to things running on localhost, which is a really useful capability for local testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/61)

use host network with start-flow.sh

---

local/start-component.sh

Currently, as far as I could tell, nothing is actually responsible for building this if you just clone all the repositories and run `start-flow.sh`, so for obvious reasons things fail to start up properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/62)

start-component.sh: Build the `fetch-open-graph` binary

---

supabase/functions/oauth/access-token.ts

Sometimes the response of servers is not JSON when there is an issue. We need logs to troubleshoot such cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/70)

oauth: add logs to access-token in case of parsing failure

---

crates/agent/src/publications/specs.rs

If a spec was published previously but is currently deleted, don't allow for it to be re-created. This is a temporary measure until we implement data plane pet-names.
Proper unit testing of this area is currently awkward: a larger project that's out of scope. Tested on a local stack by creating a capture, deleting it, and then attempting to re-create it in the UI.
Issue #65
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/71)

publications: disallow re-creation of a deleted spec

---

supabase/functions/_shared/helpers.ts

add a new helper `base64encode`, since sometimes we need to encode some headers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/72)

oauth: add template helper base64encode

---

supabase/functions/oauth/access-token.ts

tiktok requires a POST request with no body
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/animated-carnival/73)

oauth: allow access token requests without body
